
tasks:
  - init: npm install && npm run build
    command: |
      export HMR_HOST=`gp url 300`
      npm run dev
    
vscode:
  extensions:
    - dbaeumer.vscode-eslint

ports:
  - port: 3000
    onOpen: open-browser

github:
  prebuilds:
    main: true
    branches: true
    pullRequests: true